class Events:
    NEW_PLAYER = 'new_player'
    NEW_MASTER = 'new_master'
    PLAYER_QUIT = 'player_quit'
    GAME_STARTED = 'game_started'
    GAME_ABORTED = 'game_aborted'
    GAME_FINISHED = 'game_finished'
    LOST_CONNECTION = 'lost_connection'
    NEW_ROUND = 'new_round'
    PLAYER_PICKED_WORD = 'player_picked_word'
    PLAYER_ROLE_ASSIGNED = 'player_role_assigned'
    ROUND_RESOLVED = 'round_resolved'
